export const zoneOptions = [
  { value: "North", label: "North" },
  { value: "South", label: "South" },
  { value: "East", label: "East" },
  { value: "West", label: "West" },
  { value: "Central", label: "Central" },
];

export const ratingOptions = [
  { value: "Will Return", label: "Will Return" },
  { value: "Can Return", label: "Can Return" },
  { value: "Won't Return", label: "Won't Return" },
  { value: "nil", label: "nil / Collab" },
];

export const mrtOptions = [
  { value: "Admiralty", label: "Admiralty" },
  { value: "Aljunied", label: "Aljunied" },
  { value: "Ang Mo Kio", label: "Ang Mo Kio" },
  { value: "Bartley", label: "Bartley" },
  { value: "Bayfront", label: "Bayfront" },
  { value: "Beauty World", label: "Beauty World" },
  { value: "Bedok", label: "Bedok" },
  { value: "Bedok North", label: "Bedok North" },
  { value: "Bedok Reservoir", label: "Bedok Reservoir" },
  { value: "Bencoolen", label: "Bencoolen" },
  { value: "Bendemeer", label: "Bendemeer" },
  { value: "Bishan", label: "Bishan" },
  { value: "Boon Keng", label: "Boon Keng" },
  { value: "Boon Lay", label: "Boon Lay" },
  { value: "Botanic Gardens", label: "Botanic Gardens" },
  { value: "Braddell", label: "Braddell" },
  { value: "Bras Basah", label: "Bras Basah" },
  { value: "Buangkok", label: "Buangkok" },
  { value: "Bugis", label: "Bugis" },
  { value: "Bukit Batok", label: "Bukit Batok" },
  { value: "Bukit Gombak", label: "Bukit Gombak" },
  { value: "Bukit Panjang", label: "Bukit Panjang" },
  { value: "Buona Vista", label: "Buona Vista" },
  { value: "Caldecott", label: "Caldecott" },
  { value: "Canberra", label: "Canberra" },
  { value: "Cashew", label: "Cashew" },
  { value: "Changi Airport", label: "Changi Airport" },
  { value: "Chinatown", label: "Chinatown" },
  { value: "Chinese Garden", label: "Chinese Garden" },
  { value: "Choa Chu Kang", label: "Choa Chu Kang" },
  { value: "City Hall", label: "City Hall" },
  { value: "Clarke Quay", label: "Clarke Quay" },
  { value: "Clementi", label: "Clementi" },
  { value: "Commonwealth", label: "Commonwealth" },
  { value: "Dakota", label: "Dakota" },
  { value: "Dhoby Ghaut", label: "Dhoby Ghaut" },
  { value: "Dover", label: "Dover" },
  { value: "Downtown", label: "Downtown" },
  { value: "Esplanade", label: "Esplanade" },
  { value: "Eunos", label: "Eunos" },
  { value: "Expo", label: "Expo" },
  { value: "Farrer Park", label: "Farrer Park" },
  { value: "Farrer Road", label: "Farrer Road" },
  { value: "Fort Canning", label: "Fort Canning" },
  { value: "Geylang Bahru", label: "Geylang Bahru" },
  { value: "Gul Circle", label: "Gul Circle" },
  { value: "HarbourFront", label: "HarbourFront" },
  { value: "Haw Par Villa", label: "Haw Par Villa" },
  { value: "Hillview", label: "Hillview" },
  { value: "Holland Village", label: "Holland Village" },
  { value: "Hougang", label: "Hougang" },
  { value: "Jalan Besar", label: "Jalan Besar" },
  { value: "Joo Koon", label: "Joo Koon" },
  { value: "Jurong East", label: "Jurong East" },
  { value: "Kaki Bukit", label: "Kaki Bukit" },
  { value: "Kallang", label: "Kallang" },
  { value: "Kembangan", label: "Kembangan" },
  { value: "Kent Ridge", label: "Kent Ridge" },
  { value: "Khatib", label: "Khatib" },
  { value: "King Albert Park", label: "King Albert Park" },
  { value: "Kovan", label: "Kovan" },
  { value: "Kranji", label: "Kranji" },
  { value: "Labrador Park", label: "Labrador Park" },
  { value: "Lakeside", label: "Lakeside" },
  { value: "Lavender", label: "Lavender" },
  { value: "Little India", label: "Little India" },
  { value: "Lorong Chuan", label: "Lorong Chuan" },
  { value: "MacPherson", label: "MacPherson" },
  { value: "Marina Bay", label: "Marina Bay" },
  { value: "Marina South Pier", label: "Marina South Pier" },
  { value: "Marsiling", label: "Marsiling" },
  { value: "Marymount", label: "Marymount" },
  { value: "Mattar", label: "Mattar" },
  { value: "Mountbatten", label: "Mountbatten" },
  { value: "Newton", label: "Newton" },
  { value: "Nicoll Highway", label: "Nicoll Highway" },
  { value: "Novena", label: "Novena" },
  { value: "Orchard", label: "Orchard" },
  { value: "Outram Park", label: "Outram Park" },
  { value: "Pasir Panjang", label: "Pasir Panjang" },
  { value: "Pasir Ris", label: "Pasir Ris" },
  { value: "Paya Lebar", label: "Paya Lebar" },
  { value: "Pioneer", label: "Pioneer" },
  { value: "Potong Pasir", label: "Potong Pasir" },
  { value: "Promenade", label: "Promenade" },
  { value: "Punggol", label: "Punggol" },
  { value: "Queenstown", label: "Queenstown" },
  { value: "Raffles Place", label: "Raffles Place" },
  { value: "Redhill", label: "Redhill" },
  { value: "Rochor", label: "Rochor" },
  { value: "Sembawang", label: "Sembawang" },
  { value: "Sengkang", label: "Sengkang" },
  { value: "Serangoon", label: "Serangoon" },
  { value: "Simei", label: "Simei" },
  { value: "Sixth Avenue", label: "Sixth Avenue" },
  { value: "Somerset", label: "Somerset" },
  { value: "Stadium", label: "Stadium" },
  { value: "Stevens", label: "Stevens" },
  { value: "Tai Seng", label: "Tai Seng" },
  { value: "Tampines", label: "Tampines" },
  { value: "Tampines East", label: "Tampines East" },
  { value: "Tampines West", label: "Tampines West" },
  { value: "Tan Kah Kee", label: "Tan Kah Kee" },
  { value: "Tanah Merah", label: "Tanah Merah" },
  { value: "Tanjong Pagar", label: "Tanjong Pagar" },
  { value: "Telok Ayer", label: "Telok Ayer" },
  { value: "Telok Blangah", label: "Telok Blangah" },
  { value: "Tiong Bahru", label: "Tiong Bahru" },
  { value: "Toa Payoh", label: "Toa Payoh" },
  { value: "Tuas Crescent", label: "Tuas Crescent" },
  { value: "Tuas Link", label: "Tuas Link" },
  { value: "Tuas West Road", label: "Tuas West Road" },
  { value: "Ubi", label: "Ubi" },
  { value: "Upper Changi", label: "Upper Changi" },
  { value: "Woodlands", label: "Woodlands" },
  { value: "Woodlands North", label: "Woodlands North" },
  { value: "Woodlands South", label: "Woodlands South" },
  { value: "Woodleigh", label: "Woodleigh" },
  { value: "Yew Tee", label: "Yew Tee" },
  { value: "Yio Chu Kang", label: "Yio Chu Kang" },
  { value: "Yishun", label: "Yishun" },
  { value: "one-north", label: "one-north" },
];

export const overseasOptions = [
  { value: "Germany, Berlin", label: "Germany, Berlin" },
  { value: "Paris, France", label: "Paris, France" },
  { value: "Rome, Italy", label: "Rome, Italy" },
  { value: "Naples, Italy", label: "Naples, Italy" },
];
